### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by ManuelBot59** [andpalmier/makephish#2]
I try to install the tool and I get this error

ERROR:
┌──(root💀kali)-[/home/kali/TOOLS/makephish]
└─# make makephish
cmd/makephish/makephish.go:15:2: missing go.sum entry for module providing package github.com/gocolly/colly; to add:
        go mod download github.com/gocolly/colly
make: *** [makefile:4: makephish] Error 1

**Comment by andpalmier** [comment]
Thanks for testing makephish! I think I found the problem, please let me know if it's not solved.

**Comment by ManuelBot59** [comment]
Thanks for updating, now tell me to update directly, with what code do I do it?, or do I have to delete and re-clone the repository? Example: Git clone
